### ISSUE TITLE
Problema con la modifica di domande in quiz già creati

### ISSUE THREAD

**Issue by 874449** [matteospanio/Progetto-BD-2021#6]
Stavo facendo delle prove con delle domande quando mi sono accorto di questo problema. 
Sono andato nella dashboard e poi nel opzione di modificare un quiz già fatto. 
L'unica cosa che ho modificato è stata la domanda con id 14 in "prova di domanda 3" ed ora in pgadmin compare come un doppione di un altra domanda. Non è la prima volta che ho notato questa cosa.

Prima
![image](https://user-images.githubusercontent.com/88272153/129613678-c237005b-0319-4bb4-b621-b01e790fd84d.png)

Dopo
![image](https://user-images.githubusercontent.com/88272153/129614268-bc6fd28d-6428-4fbf-a8a6-6a9f05776802.png)

**Comment by matteospanio** [comment]
Stai usando la versione aggiornata dell'applicazione? Questo errore veniva fuori prima che facessi l'ultimo commit.
La parte di codice incriminata dovrebbe essere nel file app/quiz/view.py nella route editor che riporto andando a vedere dal commit `2290713`:
```python
    if editor_form.validate_on_submit():
        # editor_form.populate_obj(current_quiz)  --- it doesn't work
        current_quiz.title = editor_form.title.data
        current_quiz.description = editor_form.description.data
        i = 0
        max_len = len(current_quiz.questions.all())
        for elem in editor_form.questions.data:
            if i < max_len:
                setattr(current_quiz.questions[i], 'text', elem['text'])
                setattr(current_quiz.questions[i], 'type_id', str(elem['type_id']))
                setattr(current_quiz.questions[i], 'activant', elem['activant'])
                i = i + 1
            else:
                domanda = Domanda(text=elem['text'],
                                  type_id=str(elem['type_id']),
                                  activant=elem['activant'],
                                  quiz_id=edit_id)
                db.session.add(domanda)

        db.session.commit()
```
inizialmente la mia idea era di creare dinamicamente con javascript i campi dove mettere in input i dati delle domande, man mano che ho lavorato all'implementazione mi sono reso conto che l'idea era impostata male ed era più il tempo che passavo in cerca degli errori di quello a portare avanti l'app, così ho deciso di cambiare drasticamente la faccenda e creare le pagine statiche senza javascript (che potrebbe invece tornare utile nella parte di visualizzazione e compilazione del questionario). In particolare l'errore è dovuto al fatto che il metodo `editor_form.populate_obj()` non funziona come dovrebbe, quindi nel codice su riportato avevo scritto per esteso il metodo. Il problema è quello che segnali tu però, le domande non si aggiornano.
Nella versione aggiornata ho creato view separate per aggiungere domande e per modificarle, di modo da essere in grado di mappare correttamente le informazioni col DB.
Se invece questo problema si verifica con l'ultimo commit `548b86a` è un comportamento inaspettato...

**Comment by 874449** [comment]
Hmmm a me segna che l'ultimo commit di quel file è di 8 ore fa e che è la versione `22f8476`

**Comment by 874449** [comment]
si colpa mia, il mio master era aggiornato ma non il branch in cui stavo lavorando
